### ISSUE TITLE
Compiled lib in NPM is not the latest version, sprites not working

### ISSUE THREAD

**Issue by kanzelm3** [joshwcomeau/redux-sounds#1]
First off, I want to say that I love this middleware and I think you did an excellent job with the implementation and making it super easy to drop into any redux application. It seems as though when you install the v1.1 package via NPM, the main file from your package.json (`lib/index.js`) is actually an older version of the package. If you look at the `lib/index.js` file in node_modules, on line 35 has the following:

``` js
sounds[soundName].play();
```

This is identical to the way you called `play()` in v1.0.1 and is different than the current footprint of this file in v1.1:

``` js
const [ soundName, spriteName ] = action.meta.sound.split('.');

howlerIntegration.play(soundName, spriteName);
```

Could you please update the way that you publish your npm package so that it builds on pre-publish so that I can use the sprites? Thank you!

**Comment by joshwcomeau** [comment]
Ah! Sorry about that.

I realized how dangerous not having a prepublish is a few months ago on another project. I should've made sure to add it here as well!

`v1.1.1` includes the right files in /lib and /dist :) I can't really verify it myself right now (at React Rally), so do let me know if anything else is amiss, and feel free to close the issue if everything's good.

**Comment by kanzelm3** [comment]
React Rally?! I'm jealous, thanks man, I will pull down and confirm!

**Comment by joshwcomeau** [comment]
Going to assume it worked out :) let me know if you run into any other issues!
