### ISSUE TITLE
Can't play non-sprite sounds

### ISSUE THREAD

**Issue by mrob11** [joshwcomeau/redux-sounds#10]
I cannot get this library to actually play sounds in the project I'm working on so I created a [minimal reproduction repo](https://github.com/mike360/redux-sounds-issue) just trying to get the library working at all.

The mp3 files are loaded (can see via network tab), but do not play when action fires.

There is a warning in the Chrome inspector:
> The Web Audio autoplay policy will be re-enabled in Chrome 70 (October 2018). Please check that your website is compatible with it. https://goo.gl/7K7WLu

But that is the only hint I have.

**Comment by mrob11** [comment]
Looking a little deeper it's not at all likely that this has anything to do with the Chrome inspector warning. All the same, I don't know if something has happened with respect to dependency compatibility or what but I can't get the most basic example working.

**Comment by GeKorm** [comment]
It's a redux-sounds bug, I'll post a workaround in a minute and a fix within the week. Sorry about that and thanks for the bug report and repro.

**Comment by mrob11** [comment]
Cool, thanks for the reply. Really like the simplicity of this library, presuming it'll work :)

**Comment by GeKorm** [comment]
So the first issue is wrong documentation in the very first example 🙃 It shouldn't be `meta: { sound: "foo" }` but `meta: { sound: { play: "foo" } }` The other examples include it, but I forgot to update this one.

The second is a bug with simple sounds. Sprites work, so a workaround would be to treat your sounds as sprites until I publish a fix.  
soundsData becomes:

```javascript
{
  foo: {
    src: [require("./foo.mp3")],
    sprite: {
      start: [0, 5000] // <- [start point in millis, duration in millis]
    }
  },
}
```

And the play action: `{ type: "PLAY_SOUND", meta: { sound: { play: "foo.start" } } }`
Again apologies for the inconvenience.

**Comment by GeKorm** [comment]
Still working on this, "within the week" was slightly optimistic :)

**Comment by KennyLindahl** [comment]
@GeKorm Sorry to bug you, but do you have any ETA on this?
Currently having the same issue which is slowing down my development on my project.

Thanks in advance

**Comment by GeKorm** [comment]
@KennyLindahl I'll work on this today, so I expect to publish the new version tomorrow

**Comment by KennyLindahl** [comment]
@GeKorm Thanks for your update, much appreciated

**Comment by GeKorm** [comment]
@mike360 @KennyLindahl 
I just published 3.0.1
Please let me know if it solves the issue for you, or if you have any questions

**Comment by KennyLindahl** [comment]
@GeKorm 

Got this when i run my project with redux-sounds `v3.0.1`:
```
🚨  /my-project/node_modules/redux-sounds/node_modules/howler/dist/howler.js: ENOENT: 
no such file or directory, open '/my-project/node_modules/redux-sounds/node_modules/howler/dist/howler.js'
```

It works when i revert to redux-sounds`v3.0.0`.
I have howler `v2.0.15` in my dependencies.

**Comment by GeKorm** [comment]
Huh must've messed up with webpack lemme check

**Comment by GeKorm** [comment]
@KennyLindahl

I can't reproduce this actually, not in my repos nor in Mike's repo above. What's your setup? Can you try removing Howler (it's not a peer dependency) and maybe remove node_modules/ and clear your npm/yarn cache before re-installing?

**Comment by KennyLindahl** [comment]
@GeKorm Thanks for the feedback. Yep, then it must be on my side. I removed node_modules and re-installed with yarn and still got the error.
I will have a look at i later, thanks.

**Comment by KennyLindahl** [comment]
@GeKorm It works as expected after clearing my yarn cache. Thanks a lot!

**Comment by GeKorm** [comment]
Yay glad I could help!
