### ISSUE TITLE
Sounds relative path

### ISSUE THREAD

**Issue by piotreksko** [joshwcomeau/redux-sounds#12]
Hello
I am trying to use my sounds from a relative path.

My rootReducer is in the root
My sounds are in ./sounds
My soundsData is imported to rootReducer from ./constants/soundsData and looks like this:

export const soundsData = {
    randomSound: '../sounds/randomSound.mp3',
  }

But this way with URL works:

export const soundsData = {
   randomSound: 'www.randomsounds.com/randomSound.mp3
};

Is there a way to play sounds using a relative path?

**Comment by GeKorm** [comment]
The sound is just a URL, exactly the same as if you had an `<img src="URL" />` This means the browser will request this url (relative to your domain if no domain is specified) and your server needs to be configured to serve files in this directory. 

Depending on your build configuration (eg. webpack with the appropriate loader) you could `import / require` the sound, again like you would an image or other asset. eg `randomSound: require('../sounds/randomSound.mp3')`

**Comment by piotreksko** [comment]
Thanks, it worked.
