### ISSUE TITLE
Add new sounds after middleware created?

### ISSUE THREAD

**Issue by 0xdevalias** [joshwcomeau/redux-sounds#22]
Currently the docs talk about needing to have all the sounds added to the middleware at the beginning, but I was wondering if there is/could be a way to add/configure new sounds 'on the fly' using actions/etc?

**Comment by GeKorm** [comment]
I think there can be a way to do that, thanks for the suggestion! I'll try to get a release up in the next few days.

**Comment by GeKorm** [comment]
Hi just an update, I'll get a beta release out soon but in the meantime you can try it out on [tree/feature/add-sound](https://github.com/joshwcomeau/redux-sounds/tree/feature/add-sounds). The syntax is similar to the middleware initialization, via `action.meta.sound.add`. There's currently no support for sound callbacks like `onEnd` for sounds added this way, but I'll try to address that a bit later.

```javascript
/* add-sounds-actions.js */
const coinSoundsData = {
  heavyCoin: 'https://s3.amazonaws.com/bucketName/gold_coin.mp3',
  lightCoin: {
    src: 'https://s3.amazonaws.com/bucketName/gold_coin.mp3', // just lower volume
    volume: 0.75
  },
  randomCoins: {
    src: ['https://s3.amazonaws.com/bucketName/coin_collection.mp3'],
    sprite: {
      one: [0, 1000],
      two: [1000, 2500],
      three: [3500, 10000]
    }
  }
};

export function addCoinSounds() {
  return {
    type: 'ADD_COIN_SOUNDS',
    meta: {
      sound: {
        add: coinSoundsData
      }
    }
  };
}


/* MyComponent.js */

dispatch(addCoinSounds());
```

**Comment by GeKorm** [comment]
Now out of beta in 3.3.0!
