### ISSUE TITLE
Looped sounds can't be addressed after completing their first loop

### ISSUE THREAD

**Issue by rovenko** [joshwcomeau/redux-sounds#26]
When using a looped sound, it's only possible to address the sound (i.e. fade / stop) only when the very first iteration of the loop is being played back.
As soon as the sound goes into the second iteration of the loop, the same control actions stop working.

**Comment by rovenko** [comment]
Howler's onend Function fires when the sound finishes playing (if it is looping, it'll fire at the end of each loop). The first parameter is the ID of the sound.
redux-sounds, uses "onend" handler that calls this.removeId(id) therefore removing it from the list and making it unavailable.
Given that there's "onstop" - is removeId(id) necessary for "onend"?

**Comment by ludgerey** [comment]
Any feasible workarounds for this?

Being unable to stop sounds makes this library not applicable for background music.

**Comment by rovenko** [comment]
> Any feasible workarounds for this?
> 
> Being unable to stop sounds makes this library not applicable for background music.

I've applied a git patch to to fix it in my local repo.

Simply comment out __this2.removeId(id);_ and _this.removeId(id);_ in relevant spots in howler_integration.js and it seems to do the trick.

**Comment by ludgerey** [comment]
@rovenko Thanks for the heads up!

I got it fixed and added a pull request that supports looped sounds.

**Comment by GeKorm** [comment]
Merged #28. I'll release the fix in a few days, thank you both for the bug report and PR, I really appreciate the help!

**Comment by GeKorm** [comment]
3.3.0 Published to npm!
