### ISSUE TITLE
An array of source files must be passed with any new Howl.

### ISSUE THREAD

**Issue by brycemonster** [joshwcomeau/redux-sounds#5]
Getting this error after upgrading to v2 of redux-sounds. Any ideas. Was working fine prior to update. Used yarn as suggested. 

Thx!
Bryce

**Comment by GeKorm** [comment]
In your soundsData object, are you using `src: ['sound1.mp3']` or something similar? Note that v2 has a breaking change where you have to rename `urls` to `src`.

**Comment by brycemonster** [comment]
You're correct, my fault. Thanks!
