### ISSUE TITLE
how can i create many sound trigger a action?

### ISSUE THREAD

**Issue by bigfatpanda1994** [joshwcomeau/redux-sounds#6]

**Comment by GeKorm** [comment]
Afraid I don't understand. Are you trying to chain sounds and actions?

**Comment by bigfatpanda1994** [comment]
yep GeKorm, that 's my problem. Can you help me ?

**Comment by bigfatpanda1994** [comment]
currently, i dispatch chain actions and setTimeout for them, but sounds is incoherent

**Comment by GeKorm** [comment]
@bigfatpanda1994 I see, I'll push a release in a few minutes that supports all [Howler methods](https://github.com/goldfire/howler.js#methods). I think you can solve your problem using `on()`

**Comment by GeKorm** [comment]
Hey @bigfatpanda1994 version 3.0.0 has been published with the above feature. Let me know if you have any problems with it.
